# Generated by Django 3.2.16 on 2023-05-23 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0038_auto_20230209_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(help_text='Last annotator or reviewer who updated this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assign', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
    ]
