name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: github_deploy
          environment_name: Githubdeploy-env
          version_label: "Sample-2"
          region: ap-southeast-2
          deployment_package: Dockerrun.aws.json
          use_existing_version_if_available: true
          

